import {type Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryLayout from "@/components/model/providers/QueryLayout";
import ChakraLayout from "@/components/model/providers/ChakraLayout";
import {type NextFont } from "next/dist/compiled/@next/font";

const inter:NextFont = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Film App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}
       style={{
        backgroundColor:"black",
        minWidth:540
        }}>
        <QueryLayout>
          <ChakraLayout> 
            {children}
          </ChakraLayout>
        </QueryLayout>
      </body>
    </html>
  );
}
